# Generated by `hip-cargo transpile` — do not edit.
# Source recipe: tests/fixtures/transpile/recipes/linear_ok.yml

"""Typer driver CLI for the 'demo' pipeline."""

import uuid
from pathlib import Path
from typing import Annotated, NewType

import typer

from hip_cargo import parse_upath

Directory = NewType("Directory", Path)

app = typer.Typer(help="Transpiled driver for the 'demo' recipe.")


@app.command()
def run(
    base_dir: Annotated[
        Directory,
        typer.Option(
            ...,
            parser=parse_upath,
            help="",
        ),
    ],
    memory_mode: Annotated[
        str,
        typer.Option(
            help="",
        ),
    ] = "greedy",
    factor: Annotated[
        float,
        typer.Option(
            help="",
        ),
    ] = 2.0,
    monitor: Annotated[
        bool,
        typer.Option(
            help="Stream progress events to the monitoring aggregator.",
        ),
    ] = False,
    job_id: Annotated[
        str | None,
        typer.Option(
            help="Fixed job id (useful for following a run live).",
        ),
    ] = None,
    ray_address: Annotated[
        str | None,
        typer.Option(
            help="Ray cluster address; omit to start/use a local cluster.",
        ),
    ] = None,
):
    """Run the 'demo' pipeline on a Ray cluster."""
    from fakepkg.transpiled.runner import run_pipeline

    if job_id is None:
        job_id = uuid.uuid4().hex[:8]
    typer.echo(f"job_id={job_id}")
    run_pipeline(
        base_dir=str(base_dir),
        memory_mode=memory_mode,
        factor=factor,
        monitor=monitor,
        job_id=job_id,
        ray_address=ray_address,
    )
    typer.echo(f"pipeline complete: job_id={job_id}")
