# Generated by `hip-cargo transpile` — do not edit.
# Source recipe: tests/fixtures/transpile/recipes/linear_ok.yml

"""ObjectRef-chaining pipeline runner for the 'demo' recipe."""

import os

os.environ.setdefault("RAY_ENABLE_UV_RUN_RUNTIME_ENV", "0")

import uuid  # noqa: E402

from hip_cargo.utils.progress import EventType, ProgressEvent, emit  # noqa: E402

STEPS = ["first", "second"]
EDGES = [["first", "second"]]


def _emit(event_type: EventType, job_id: str, worker_name: str, message: str = "", extra: dict | None = None) -> None:
    """Emit a pipeline-level event through the active backend."""
    emit(
        ProgressEvent(job_id=job_id, worker_name=worker_name, event_type=event_type, message=message, extra=extra or {})
    )


def run_pipeline(
    base_dir: str,
    memory_mode: str = "greedy",
    factor: float = 2.0,
    monitor: bool = False,
    job_id: str | None = None,
    ray_address: str | None = None,
) -> "tuple[str, object]":
    """Run the 'demo' pipeline on a Ray cluster; returns (job_id, final ObjectRef)."""
    import ray
    from fakepkg.transpiled import tasks

    if job_id is None:
        job_id = uuid.uuid4().hex[:8]
    if not ray.is_initialized():
        ray.init(address=ray_address, namespace="fakepkg", ignore_reinit_error=True)
    if monitor:
        from hip_cargo.monitoring.ray_backend import RayProgressBackend, get_or_create_aggregator
        from hip_cargo.utils.progress import set_backend

        set_backend(RayProgressBackend(get_or_create_aggregator()))

    base_dir = str(base_dir)
    os.makedirs(base_dir, exist_ok=True)

    _emit(
        EventType.PIPELINE_STARTED,
        job_id,
        "demo",
        message=f"memory_mode={memory_mode}",
        extra={"steps": STEPS, "edges": EDGES, "memory_mode": memory_mode},
    )

    _emit(EventType.STEP_STARTED, job_id, "first", extra={"step_index": 0})
    ref_first = tasks.first_task.remote(memory_mode, job_id, base_dir, monitor)
    ray.wait([ref_first])
    _emit(EventType.STEP_COMPLETED, job_id, "first", extra={"step_index": 0})

    _emit(EventType.STEP_STARTED, job_id, "second", extra={"step_index": 1})
    ref_second = tasks.second_task.remote(ref_first, memory_mode, job_id, base_dir, monitor, factor=factor)
    ray.wait([ref_second])
    _emit(EventType.STEP_COMPLETED, job_id, "second", extra={"step_index": 1})

    _emit(EventType.COMPLETED, job_id, "demo", message="pipeline complete")
    return job_id, ref_second
