# Generated by `hip-cargo transpile` — do not edit.
# Source recipe: tests/fixtures/transpile/recipes/linear_ok.yml

"""Per-step @ray.remote task wrappers for the 'demo' pipeline."""

import os

os.environ.setdefault("RAY_ENABLE_UV_RUN_RUNTIME_ENV", "0")

import ray  # noqa: E402


def _activate_backend() -> None:
    """Register the shared aggregator backend inside this worker process."""
    from hip_cargo.monitoring.ray_backend import RayProgressBackend, get_or_create_aggregator
    from hip_cargo.utils.progress import set_backend

    set_backend(RayProgressBackend(get_or_create_aggregator()))


@ray.remote
def first_task(memory_mode: str, job_id: str, work_dir: str, monitor: bool) -> "object":
    """Run step 'first' (cab 'alpha') in-memory."""
    if monitor:
        _activate_backend()
    import time as _time

    _t0 = _time.perf_counter()
    from fakepkg.core.alpha import alpha_inmem

    if monitor:
        from hip_cargo.utils.diagnostics import annotate_diagnostics

        annotate_diagnostics(import_s=_time.perf_counter() - _t0, requested={"num_cpus": 1}, memory_mode=memory_mode)
    return alpha_inmem(memory_mode, job_id, job_id, work_dir)


@ray.remote
def second_task(
    dataset: "object", memory_mode: str, job_id: str, work_dir: str, monitor: bool, factor: float
) -> "object":
    """Run step 'second' (cab 'beta') in-memory."""
    if monitor:
        _activate_backend()
    import time as _time

    _t0 = _time.perf_counter()
    from fakepkg.core.beta import beta_inmem

    if monitor:
        from hip_cargo.utils.diagnostics import annotate_diagnostics

        annotate_diagnostics(import_s=_time.perf_counter() - _t0, requested={"num_cpus": 1}, memory_mode=memory_mode)
    return beta_inmem(dataset, memory_mode, job_id, job_id, work_dir, factor=factor)
