"""Tests for ``generate-schemas``.

Covers the positive path on the canonical tunable fixture, the type-whitelist
rejection of unsupported tunable types, and idempotency.
"""

import tempfile
import textwrap
from pathlib import Path

import pytest

from hip_cargo.core.generate_schemas import (
    TunableTypeError,
    _render_schema_module,
    generate_schemas,
)
from hip_cargo.utils.introspector import parse_module

FIXTURE_CLI = Path("tests/fixtures/src/fixture_pkg/cli/tunable_demo.py")
EXPECTED_TUNABLE_DEMO = textwrap.dedent('''\
    """Auto-generated by hip-cargo. Do not edit by hand."""

    from pydantic import BaseModel, Field


    class TunableDemoTunables(BaseModel):
        n_iter: int = Field(default=10, description="Number of iterations.")
        threshold: float = Field(default=0.001, description="Convergence threshold.")
''')


def _command_spec_from_source(source: str):
    """Parse an inline Python module string and return its only CommandSpec."""
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
        f.write(source)
        tmp_path = Path(f.name)
    try:
        module_spec = parse_module(tmp_path)
        assert len(module_spec.commands) == 1
        return module_spec.commands[0]
    finally:
        tmp_path.unlink()


def test_generate_schemas_writes_expected_file():
    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp)
        generate_schemas(
            [FIXTURE_CLI],
            output_dir=out_dir,
            config_file=Path("pyproject.toml"),
        )
        result = (out_dir / "tunable_demo.py").read_text()

    assert result == EXPECTED_TUNABLE_DEMO
    compile(result, "tunable_demo.py", "exec")


def test_generate_schemas_is_idempotent():
    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp)
        generate_schemas([FIXTURE_CLI], output_dir=out_dir, config_file=Path("pyproject.toml"))
        first = (out_dir / "tunable_demo.py").read_text()
        first_mtime = (out_dir / "tunable_demo.py").stat().st_mtime_ns

        generate_schemas([FIXTURE_CLI], output_dir=out_dir, config_file=Path("pyproject.toml"))
        second = (out_dir / "tunable_demo.py").read_text()
        second_mtime = (out_dir / "tunable_demo.py").stat().st_mtime_ns

    assert first == second
    # Idempotency: byte-compare-before-write keeps mtime unchanged on a no-op run.
    assert first_mtime == second_mtime


def test_generate_schemas_skips_commands_with_no_tunables():
    """Commands with zero tunable params produce no output file."""
    source = textwrap.dedent('''
        from typing import Annotated

        import typer

        from hip_cargo import stimela_cab


        @stimela_cab(name="no_tunables", info="Has no tunable params.")
        def no_tunables(
            label: Annotated[str, typer.Option(help="A label.")] = "x",
        ):
            """Has no tunable params."""
            pass
    ''')
    cmd = _command_spec_from_source(source)
    assert _render_schema_module(cmd) is None


def test_render_supports_full_type_whitelist():
    """int, float, str, bool, Literal, ListInt/Float/Str, list[int|float|str|bool], | None."""
    source = textwrap.dedent('''
        from typing import Annotated, Literal

        import typer

        from hip_cargo import ListFloat, ListInt, ListStr, StimelaMeta, stimela_cab


        @stimela_cab(name="all_types", info="Exercises every allowed tunable type.")
        def all_types(
            an_int: Annotated[
                int, typer.Option(help="i"), StimelaMeta(metadata={"tunable": True}),
            ] = 1,
            a_float: Annotated[
                float, typer.Option(help="f"), StimelaMeta(metadata={"tunable": True}),
            ] = 1.5,
            a_str: Annotated[
                str, typer.Option(help="s"), StimelaMeta(metadata={"tunable": True}),
            ] = "x",
            a_bool: Annotated[
                bool, typer.Option(help="b"), StimelaMeta(metadata={"tunable": True}),
            ] = False,
            a_literal: Annotated[
                Literal["fast", "slow"],
                typer.Option(help="lit"),
                StimelaMeta(metadata={"tunable": True}),
            ] = "fast",
            list_int: Annotated[
                ListInt, typer.Option(help="li"), StimelaMeta(metadata={"tunable": True}),
            ] = "1,2,3",
            list_float: Annotated[
                ListFloat, typer.Option(help="lf"), StimelaMeta(metadata={"tunable": True}),
            ] = "0.5,1.5",
            list_str: Annotated[
                ListStr, typer.Option(help="ls"), StimelaMeta(metadata={"tunable": True}),
            ] = "a,b",
            list_native: Annotated[
                list[int],
                typer.Option(help="ln"),
                StimelaMeta(metadata={"tunable": True}),
            ] = [1, 2],
            opt_int: Annotated[
                int | None,
                typer.Option(help="oi"),
                StimelaMeta(metadata={"tunable": True}),
            ] = None,
        ):
            """Exercises every allowed tunable type."""
            pass
    ''')
    cmd = _command_spec_from_source(source)
    rendered = _render_schema_module(cmd)
    assert rendered is not None

    # Spot-check the important type mappings.
    assert "an_int: int = Field(default=1" in rendered
    assert "a_float: float = Field(default=1.5" in rendered
    assert "a_str: str = Field(default='x'" in rendered
    assert "a_bool: bool = Field(default=False" in rendered
    assert 'a_literal: Literal["fast", "slow"]' in rendered or "a_literal: Literal['fast', 'slow']" in rendered
    assert "list_int: list[int] = Field(default=[1, 2, 3]" in rendered
    assert "list_float: list[float] = Field(default=[0.5, 1.5]" in rendered
    assert "list_str: list[str] = Field(default=['a', 'b']" in rendered
    assert "list_native: list[int] = Field(default=[1, 2]" in rendered
    assert "opt_int: int | None = Field(default=None" in rendered

    compile(rendered, "all_types.py", "exec")


@pytest.mark.parametrize(
    "annotation, default, name",
    [
        # File / Directory / MS / URI / Path are all path-shaped UPath types we reject.
        ("File | None", "None", "config_path"),
        ("Directory | None", "None", "out_dir"),
        ("MS | None", "None", "ms"),
        ("URI | None", "None", "uri"),
    ],
)
def test_rejects_path_typed_tunables(annotation, default, name):
    source = textwrap.dedent(f'''
        from typing import Annotated, NewType
        from pathlib import Path

        import typer

        from hip_cargo import StimelaMeta, parse_upath, stimela_cab

        File = NewType("File", Path)
        Directory = NewType("Directory", Path)
        MS = NewType("MS", Path)
        URI = NewType("URI", Path)


        @stimela_cab(name="bad_path", info="Tunable on a path type.")
        def bad_path(
            {name}: Annotated[
                {annotation},
                typer.Option(parser=parse_upath, help="..."),
                StimelaMeta(metadata={{"tunable": True}}),
            ] = {default},
        ):
            """Tunable on a path type."""
            pass
    ''')
    cmd = _command_spec_from_source(source)
    with pytest.raises(TunableTypeError, match="unsupported type"):
        _render_schema_module(cmd)


def test_rejects_tunable_with_typer_callback():
    source = textwrap.dedent('''
        from typing import Annotated

        import typer

        from hip_cargo import StimelaMeta, stimela_cab


        def _validate(value):
            return value


        @stimela_cab(name="bad_callback", info="Tunable with a typer callback.")
        def bad_callback(
            n: Annotated[
                int,
                typer.Option(help="n", callback=_validate),
                StimelaMeta(metadata={"tunable": True}),
            ] = 1,
        ):
            """Tunable with a typer callback."""
            pass
    ''')
    cmd = _command_spec_from_source(source)
    with pytest.raises(TunableTypeError, match="callback"):
        _render_schema_module(cmd)
